# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e054029b00521010e4f9b5f0e9196f38ccad2d88446eb1ca2d87f03a2d89a982ac0ab74ce649c86b54fe802bf5dddea10fe6936136f298aa947b7888d22609

test:
  secret_key_base: c2efc711fe8e91877093a1d4ea8d05c164351c30513df2e91fdda4d04c963d6b0fe6c9ba380b99c2f31e294ec3e9c2afe5cfe92d50a392de753b739981492a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
